#source 'git@github.com:followanalytics/fa-build-private-pods.git'
#source 'git@github.com:bryjai/bryj-build-private-pods'
#source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '14.0'

target 'Build-V3-Plugin-Monitoring-ios_Example' do
  pod 'Build-V3-Plugin-Monitoring-ios', :path => '../'
  pod 'Build-V3-Plugin-Monitoring-ios/FirebasePerformance', :path => '../'
  pod 'Build-V3-Plugin-Monitoring-ios/GROW', :path => '../'
  pod 'FASDKBuild-ios', '3.9.5', :source => 'git@github.com:bryjai/bryj-build-private-pods.git'
  target 'Build-V3-Plugin-Monitoring-ios_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
  end
end
